<?php

/**
 * @file
 * Code for the Professional Reviews feature.
 */

/**
 * Implements hook_help().
 */
function professional_reviews_help($path, $arg) {
  switch ($path) {
    case 'admin/content/professional-reviews':
      return '<p>' . t('This page provides administration actions to manage professional reviews submitted by attorneys and other professionals.') . '</p>';
  }
}

/**
 * Implements hook_views_api().
 */
function professional_reviews_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'professional_reviews') . '/includes/views',
    'template path' => drupal_get_path('module', 'professional_reviews') . '/templates',
  );
}

/**
 * Implement hook_form()
 */
function professional_review_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_node_info()
 */
function professional_reviews_node_info() {
  return array(
    'professional_review' => array(
      'name' => t('Professional review'),
      'base' => 'professional_review',
      'description' => t('Use <em>Profesionnal Reviews</em> to create reviews submitted by attorneys and other professionals.'),
      'has_title' => TRUE,
      'title_label' => t('Professional\'s name'),
    )
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function professional_reviews_preprocess_views_view_field(&$variables) {
  global $language;
  $display = $variables['view']->current_display;
  $name = $variables['view']->name;
  $row = $variables['row'];

  $professional_reviews = array(
    'block' => 'frontpage_block',
    'page_1' => 'administrative_page',
    'page_2' => 'public_page',
  );

  if ($name == 'professional_reviews') {
    $variables['theme_hook_suggestions'][] = "views_view_field__professional_reviews__$professional_reviews[$display]";
    $field_data_url = $row->_field_data['nid']['entity']->field_professional_review_url;
    $language = isset($field_data_url['#language']) ? $field_data_url['#language'] : LANGUAGE_NONE;
    $url = isset($field_data_url[$language][0]['value']) ? $field_data_url[$language][0]['value'] : 0;
    $review = $row->field_body[0]['raw'];
    $reviewer = $row->node_title;

    $variables['professional_review'] = array(
      'reviewer' => $reviewer,
      'review' => $review['value'],
    );

    if ($url) {
      $variables['professional_review']['reviewer'] = l(t('@reviewer', array(
        '@reviewer' => $reviewer
      )), $url, array(
        'attributes' => array(
          'target' => '_blank'
        ),
      ));
    }

    if ($professional_reviews[$display] == 'frontpage_block') {
      $variables['professional_review']['review'] = $review['summary'];
    }
  }
}
