<?php

/**
 * @file
 * Install, update, and uninstall functions for Registration validation module.
 */

/**
 * Implements hook_requirements().
 */
function registration_validation_requirements($phase) {
  $requirements = array();
  $t = get_t();
  if ($phase == 'runtime') {
    // Show the validation blocked counter on the status report page.
    $requirements['registration_validation_counter'] = array(
      'title' => $t('Registration Validation'),
      'value' => format_plural(
        variable_get('registration_validation_counter', 0),
        '1 blocked blacklisted domain registration',
        '@count blocked blacklisted domain registrations'
      ),
      'severity' => REQUIREMENT_INFO,
    );
  }
  return $requirements;
}

/**
 * Implements hook_install().
 */
function registration_validation_install() {
  $t = get_t();

  // Be friendly to your users: what to do after install?
  drupal_set_message($t('You can now <a href="!validation_admin">configure</a> the Registration validation module for your site.', array(
    '!validation_admin' => url('admin/config/people/registration-validation'),
  )), 'status');

}

/**
 * Implements hook_uninstall().
 */
function registration_validation_uninstall() {
  // Remove our entries from the variable table and clear the variable cache.
  db_delete('variable')
    ->condition('name', "registration_validation_%", "LIKE")
    ->execute();
  cache_clear_all('variables', 'cache');
}
