<?php
/**
 * @file
 * Module name ndsbs_change_password.module
 * Finoit Technologies
 * Developer krishna@finoit.com
 * Allows developer to customize the site's functionality.
 */


/*
 *  Implementation of hook_menu()
 *  Function ndsbs_custom_menu() defined
 *  Parameter no
 */
function ndsbs_change_password_menu() {
    $items = array();
    $items['user/change/password'] = array(
        'title'           => 'Change Password',
        'description'     => 'User change password page.',
        'access callback' => 'user_is_logged_in',
        'page callback'   => '_user_change_password_custom',
        'access arguments' => array('access content'),
    );
    
    return $items;
}

/*
 *  Implementation of hook_theme()
 *  Function ndsbs_custom_theme() defined
 *  Parameter no
 */
function ndsbs_change_password_theme() {
    $items = array();
    $items['user_change_password_form'] = array(
        'render element' => 'form',
        'template' => 'user_change_password_form',
    );
    
    return $items;
}

/*
 *  Implementation of _user_change_password_custom()
 *  Function _user_change_password_custom() defined
 *  To change the user password
 *  Parameter no
 */
function _user_change_password_custom() {
    return drupal_get_form('user_change_password_form');
}

/*
 *  Implementation of user_change_password_form()
 *  Function user_change_password_form() defined
 *  To create the change password form
 *  Parameter no
 */
function user_change_password_form($form, &$form_state) {
    // Get the currently logged in user object.
    $form['#account'] = $GLOBALS['user'];

    // Textfield cor current password confirmation.
    $form['current_pass'] = array(
        '#type' => 'password',
        '#title' => t('Current password'),
        '#size' => 25,
        '#required' => TRUE
    );

    // Password confirm field.
    $form['account']['pass'] = array(
        '#type' => 'password_confirm',
        '#size' => 25,
        '#required' => TRUE
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit')
    );
    return $form;
}

/*
 *  Validate handler for user_change_password_form().
 * 
 */
function user_change_password_form_validate(&$form, &$form_state) {
    // Make sure the password functions are present.
    require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');

    // Make sure the provided current password is valid for this account.
    if (!user_check_password($form_state['values']['current_pass'], $form['#account'])) {
        form_set_error('current_pass', t('The current password you provided is incorrect.'));
    }
    $pass_length = strlen($form_state['values']['pass']);
    if($pass_length < 6) {
        form_set_error('pass', t('The password is too short: it must be at least 6 characters.'));
    }
}

 /*
  * Submit handler for user_change_password_form().
  * 
  */
function user_change_password_form_submit(&$form, &$form_state) {
  // Set up the edit array to pass to user_save()
  $edit = array('pass' => $form_state['values']['pass']);

  // Save the account with the new password.
  user_save($form['#account'], $edit);

  // Inform the user.
  drupal_set_message(t('Your password has been changed.'));
}