<?php
/**
 * @file
 * Code for the ndsbs_videos feature.
 */

include_once 'ndsbs_videos.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 */
function ndsbs_videos_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    case 'admin/content/videos':
      $item = menu_get_item('node/add/video');
      $item['title'] = t('Add video');
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
      break;
  }
}
