<?php

/**
 * @file
 * Module name ndsbs_custom_block.module
 * Finoit Technologies
 * Developer krishna@finoit.com
 * Allows developer to customize the site's functionality.
 */


/*
 *  Implementation of hook_block_info()
 *  Function ndsbs_custom_block_block_info() defined
 *  Parameter no
 */
function ndsbs_custom_block_block_info() {
    $blocks = array();
    $blocks['registartion_block'] = array(
        'info' => t('User Registration right panel Block'),
    );

    return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function ndsbs_custom_block_block_configure($delta = '') {
    $form = array();
    switch($delta) {
        case 'registartion_block' :
            // Text field form element
            $form['text_body'] = array(
                '#type' => 'text_format',
                '#title' => t('Block body'),
                '#default_value' => variable_get('text_variable', ''),
            );

            // File selection form element
            $form['file'] = array(
                '#name' => 'block_image',
                '#type' => 'managed_file',
                '#title' => t('Choose an Image File'),
                '#description' => t('Select an Image for the custom block.  Only *.gif, *.png, *.jpg, and *.jpeg images allowed.'),
                '#default_value' => variable_get('block_image_fid', ''),
                '#upload_location' => 'public://block_image/',
                '#upload_validators' => array(
                    'file_validate_extensions' => array('gif png jpg jpeg'),
                ),
            );
            break;
    }
    return $form;
}

/**
 * Implements hook_block_save().
 */
function ndsbs_custom_block_block_save($delta = '', $edit = array()) {
    switch ($delta) {
        case 'registartion_block' :
            // Saving the WYSIWYG text
            variable_set('text_variable', $edit['text_body']['value']);

            // Saving the file, setting it to a permanent state, setting a FID variable
            $file = file_load($edit['file']);
            $file->status = FILE_STATUS_PERMANENT;
            file_save($file);
            $block = block_load('ndsbs_custom_block', $delta);
            file_usage_add($file, 'ndsbs_custom_block', 'block', $block->bid);
            variable_set('block_image_fid', $file->fid);
            break;
    }
}

/**
 * Implements hook_block_view().
 */
function ndsbs_custom_block_block_view($delta = '') {
    $block = array();

    switch($delta) {
        case 'registartion_block' :
            $block['content'] = custom_block_view();
            break;
    }

    return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function custom_block_view() {
    $block = array();

    // Capture the image file path and form into HTML with attributes
    $image_file = file_load(variable_get('block_image_fid', ''));
    $image_path = '';

    if (isset($image_file->uri)) {
        $image_path = $image_file->uri;
    }

    $image = theme_image(array(
                            'path' => ($image_path),
                            'width' => '200px',
                            'height' => '135px',
                            'alt' => t('Steps to Successfully Complete an Assessment.'),
                            'title' => t('Steps to Successfully Complete an Assessment.'),
                            'attributes' => array('class' => 'thin'),
                        ));

    // Capture WYSIWYG text from the variable
    $text = variable_get('text_variable', '');

    // Block output in HTML with div wrapper
    $block = array(
        'image' => array(
            '#type' => 'markup',
            '#markup' => $image,
        ),
        'message' => array(
            '#type' => 'markup',
            '#markup' => $text,
        ),
    );

    return $block;
}