<?php

/**
 * @file
 * Provides UIkit components as CKEditor plugins.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function uikit_ckeditor_ckeditor_plugin() {
  $module_path = drupal_get_path('module', 'uikit_ckeditor');

  return array(
    'uikitAccordion' => array(
      'name' => 'uikitAccordion',
      'desc' => t('UIkit Accordion: Inserts a UIkit Accordion component.'),
      'path' => $module_path . '/plugins/uikitAccordion/',
      'buttons' => array(
        'uikitAccordion' => array(
          'label' => 'Insert UIkit Accordion',
          'icon' => 'icons/uikit-accordion.png',
        ),
      ),
      'load' => TRUE,
    ),
  );
}
