<?php

/**
 * @file
 * NDSBS development module for use on dev.ndsbs.com only.
 */

/**
 * Implements hook_menu().
 */
function ndsbs_development_menu() {
  $items['node_two'] = array(
    'page callback' => 'node_page_default_clone',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['node_three'] = array(
    'page callback' => 'node_page_default_clone',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function ndsbs_development_block_info() {
  $blocks['frontpage_development_links'] = array(
    'info' => t('Frontpage development links'),
    'status' => 1,
    'region' => 'header',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "<front>\nnode_two\nnode_three\n",
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ndsbs_development_block_view($delta = '') {
  $block = array();
  $options_two = array();
  $options_three = array();

  switch (current_path()) {
    case 'node_two':
      $options_two['attributes']['class'][] = 'uk-active';
      break;

    case 'node_three':
      $options_three['attributes']['class'][] = 'uk-active';
      break;
  }

  $items = array(
    0 => array(
      'data' => l(t('Demo #2'), '/node_two', $options_two),
    ),
    1 => array(
      'data' => l(t('Demo #3'), '/node_three', $options_three),
    ),
  );
  $item_list = theme('item_list', array(
    'items' => $items,
    'type' => 'ul',
    'attributes' => array(
      'style' => 'position: fixed; top: 130px; right: 0; left: 90%; background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJod…BoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==);
    background: -moz-linear-gradient( top, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.7) 100%);
    background: -webkit-gradient( linear, left top, left bottom, color-stop(0%, rgba(0, 0, 0, 0.7)), color-stop(100%, rgba(0, 0, 0, 0.7)));
    background: -webkit-linear-gradient( top, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.7) 100%);
    background: -o-linear-gradient( top, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.7) 100%);
    background: -ms-linear-gradient( top, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.7) 100%);
    background: linear-gradient( to bottom, rgba(0, 0, 0, 0.7) 0%, rgba(0, 0, 0, 0.7) 100%);
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr=\'#b3000000\', endColorstr=\'#b3000000\',GradientType=0);
    padding: 20px;',
    ),
  ));

  switch ($delta) {
    case 'frontpage_development_links':
      $block['subject'] = t('');
      $block['content'] = [
        '#markup' => $item_list,
      ];
      break;
  }

  return $block;
}

/**
 * Menu callback: Generates a listing of promoted nodes.
 *
 * @return array
 *   An array in the format expected by drupal_render().
 *
 * @see node_menu()
 */
function node_page_default_clone() {
  $select = db_select('node', 'n')
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('n.promote', 1)
    ->condition('n.status', 1)
    ->orderBy('n.sticky', 'DESC')
    ->orderBy('n.created', 'DESC')
    ->extend('PagerDefault')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access');

  $nids = $select->execute()->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build = node_view_multiple($nodes);

    // 'rss.xml' is a path, not a file, registered in node_menu().
    drupal_add_feed('rss.xml', variable_get('site_name', 'Drupal') . ' ' . t('RSS'));
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
    drupal_set_title('');
  }
  else {
    drupal_set_title(t('Welcome to @site-name', array('@site-name' => variable_get('site_name', 'Drupal'))), PASS_THROUGH);

    $default_message = '<p>' . t('No front page content has been created yet.') . '</p>';

    $default_links = array();
    if (_node_add_access()) {
      $default_links[] = l(t('Add new content'), 'node/add');
    }
    if (!empty($default_links)) {
      $default_message .= theme('item_list', array('items' => $default_links));
    }

    $build['default_message'] = array(
      '#markup' => $default_message,
      '#prefix' => '<div id="first-time">',
      '#suffix' => '</div>',
    );
  }
  return $build;
}
