<?php

/**
 * @file
 * NDSBS development module for use on dev.ndsbs.com only.
 */

/**
 * Implements hook_menu().
 */
function ndsbs_development_menu() {
  $items['node_two'] = array(
    'title' => t('Demo two'),
    'page callback' => 'node_page_default_clone',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['node_three'] = array(
    'title' => t('Demo three'),
    'page callback' => 'node_page_default_clone',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/appearance/examples'] = array(
    'title' => t('Examples'),
    'page callback' => 'ndsbs_development_examples',
    'access arguments' => array('access content'),
    'menu_name' => 'management',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ndsbs_development_theme($existing, $type, $theme, $path) {
  return array(
    'examples' => array(
      'template' => 'examples',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function ndsbs_development_block_info() {
  $blocks['frontpage_development_links'] = array(
    'info' => t('Frontpage development links'),
    'status' => 1,
    'region' => 'header',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "<front>\nnode_two\nnode_three\n",
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ndsbs_development_block_view($delta = '') {
  $block = array();
  $options_two = array();
  $options_three = array();

  switch (current_path()) {
    case 'node_two':
      $options_two['attributes']['class'][] = 'uk-active';
      break;

    case 'node_three':
      $options_three['attributes']['class'][] = 'uk-active';
      break;
  }

  $items = array(
    0 => array(
      'data' => l(t('Demo #2'), '/node_two', $options_two),
    ),
    1 => array(
      'data' => l(t('Demo #3'), '/node_three', $options_three),
    ),
  );
  $item_list = theme('item_list', array(
    'items' => $items,
    'type' => 'ul',
  ));

  switch ($delta) {
    case 'frontpage_development_links':
      $block['subject'] = t('');
      $block['content'] = [
        '#markup' => $item_list,
      ];
      break;
  }

  return $block;
}

/**
 * Menu callback: Generates a listing of promoted nodes.
 *
 * @return array
 *   An array in the format expected by drupal_render().
 *
 * @see ndsbs_development_menu()
 */
function node_page_default_clone() {
  $select = db_select('node', 'n')
    ->fields('n', array('nid', 'sticky', 'created'))
    ->condition('n.promote', 1)
    ->condition('n.status', 1)
    ->orderBy('n.sticky', 'DESC')
    ->orderBy('n.created', 'DESC')
    ->extend('PagerDefault')
    ->limit(variable_get('default_nodes_main', 10))
    ->addTag('node_access');

  $nids = $select->execute()->fetchCol();
  $title = variable_get('site_frontpage_title');

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build = node_view_multiple($nodes);

    // 'rss.xml' is a path, not a file, registered in node_menu().
    drupal_add_feed('rss.xml', variable_get('site_name', 'Drupal') . ' ' . t('RSS'));
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
    drupal_set_title(t('@title', array('@title' => $title)));
  }
  else {
    drupal_set_title(t('@title', array('@title' => $title)));

    $default_message = '<p>' . t('No front page content has been created yet.') . '</p>';

    $default_links = array();
    if (_node_add_access()) {
      $default_links[] = l(t('Add new content'), 'node/add');
    }
    if (!empty($default_links)) {
      $default_message .= theme('item_list', array('items' => $default_links));
    }

    $build['default_message'] = array(
      '#markup' => $default_message,
      '#prefix' => '<div id="first-time">',
      '#suffix' => '</div>',
    );
  }
  return $build;
}

/**
 * Menu callback: Generates a page showing examples of UIkit components.
 *
 * @return array
 *   An array in the format expected by drupal_render().
 *
 * @see ndsbs_development_menu()
 */
function ndsbs_development_examples() {
  return theme('examples');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ndsbs_development_preprocess_page(&$variables) {
  if (current_path() == 'admin/appearance/examples') {
    $variables['page_description'] = t('View examples of various color schemes on UIkit components');
  }
}
